EOS.Web/Controllers/AppUsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Dynamic.Core;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EOS.Web.Data;
using EOS.Web.Models;
using System.ComponentModel.DataAnnotations;
using System.Text;
using System.Text.Encodings.Web;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using EOS.Web.Areas.Identity.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.Extensions.Logging;

namespace EOS.Web.Controllers
{
    public class AppUsersController : Controller
    {
        private readonly EOSContext _context;
        private readonly UserManager<AppUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public AppUsersController(EOSContext context, UserManager<AppUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _context = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }

        // GET: Banks
        [Authorize]
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult LoadData()
        {
            try
            {
                var draw = HttpContext.Request.Form["draw"].FirstOrDefault();
                var start = Request.Form["start"].FirstOrDefault();// Skip number of Rows count  
                var length = Request.Form["length"].FirstOrDefault(); // Paging Length 10,20  
                var sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault(); // Sort Column Name  
                var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();// Sort Column Direction (asc, desc)  
                var searchValue = Request.Form["search[value]"].FirstOrDefault(); // Search Value from (Search box)
                int pageSize = length != null ? Convert.ToInt32(length) : 0; //Paging Size (10, 20, 50,100)  
                int skip = start != null ? Convert.ToInt32(start) : 0;
                int recordsTotal = 0;

                // getting all data  
                var appUsers = (from a in _context.AppUsers
                            select a);
                //Sorting  
                if (!(string.IsNullOrEmpty(sortColumn) && string.IsNullOrEmpty(sortColumnDirection)))
                {
                    appUsers = appUsers.OrderBy(sortColumn + " " + sortColumnDirection);
                }
                //Search  
                if (!string.IsNullOrEmpty(searchValue))
                {
                    appUsers = appUsers.Where(m => m.FullName.Contains(searchValue) || m.Email.Contains(searchValue) || 
                    m.PhoneNumber.Contains(searchValue) || m.EmployeeNumber.Contains(searchValue) || m.Address.Contains(searchValue));
                }

                //total number of rows counts   
                recordsTotal = appUsers.Count();
                //Paging   
                var data = appUsers.Skip(skip).Take(pageSize).ToList();
                //Returning Json Data  
                return Json(new { draw = draw, recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = data });
            }
            catch (Exception)
            {
                throw;
            }
        }

        // GET: Banks/AddOrEdit
        [NoDirectAccess]
        public async Task<IActionResult> AddOrEdit(string id = "")
        {
            if (id == "" || id == null)//flagged as insert
            {
                PopulateSectionDropDownList();
                PopulateDepartmentDropDownList();
                PopulateDivisionDropDownList();
                PopulateJobDropDownList();
                PopulateGradeDropDownList();
                //PopulateBankDropDownList();
                UserRole usr = new UserRole();
                usr.ApplicationUser = new AppUser();
                usr.ApplicationRoles = await _roleManager.Roles.Select(x => new SelectListItem()
                {
                    Text = x.Name,
                    Value = x.Id
                }).ToListAsync();
                return View(usr);
            }
            else
            {
                UserRole userRole = new UserRole();
                //var appUser = await _context.AppUsers.FindAsync(id);
                var appUser = _context.Users.Where(x => x.Id.Equals(id)).SingleOrDefault();
                var userInRole = _context.UserRoles.Where(x => x.UserId.Equals(id)).Select(x => x.RoleId).ToList();
                userRole.ApplicationUser = appUser;
                userRole.ApplicationRoles = await _roleManager.Roles.Select(x => new SelectListItem()
                {
                    Text = x.Name,
                    Value = x.Id,
                    Selected = userInRole.Contains(x.Id)
                }).ToListAsync();
                PopulateSectionDropDownList(appUser.Section);
                PopulateDepartmentDropDownList(appUser.Department);
                PopulateDivisionDropDownList(appUser.Division);
                PopulateJobDropDownList(appUser.Job);
                PopulateGradeDropDownList(appUser.Grade);
                //PopulateBankDropDownList(appUser.Bank);
                if (appUser == null)
                {
                    return NotFound();
                }
                return View(userRole);
            }
        }

        // POST: AppUsers/AddOrEdit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public async Task<IActionResult> AddOrEdit(string id, [Bind("UserName,Email,PhoneNumber,FullName,BirthPlace,BirthDate,EmployeeNumber,StartJoinDate,EndJoinDate,Address,SectionId,DepartmentId,DivisionId,JobId,GradeId,BankId")] UserRole appUser)
        public async Task<IActionResult> AddOrEdit(string id, UserRole userRole)
        {
            if (ModelState.IsValid)
            {
                if (IdExists(id)) //update
                {
                    try {
                        var usr = await _userManager.FindByIdAsync(id);
                        var selectedRoleId = userRole.ApplicationRoles.Where(x => x.Selected).Select(x => x.Value);
                        var alreadyExists = _context.UserRoles.Where(x => x.UserId.Equals(id)).Select(x => x.RoleId).ToList();
                        var toAdd = selectedRoleId.Except(alreadyExists);
                        var toRemove = alreadyExists.Except(selectedRoleId);

                        //update app users
                        usr.FullName = userRole.ApplicationUser.FullName;
                        usr.UserName = userRole.ApplicationUser.UserName;
                        usr.StartJoinDate = userRole.ApplicationUser.StartJoinDate;
                        usr.Email = userRole.ApplicationUser.Email;
                        usr.EmployeeNumber = userRole.ApplicationUser.EmployeeNumber;
                        usr.SectionId = userRole.ApplicationUser.SectionId;
                        usr.DepartmentId = userRole.ApplicationUser.DepartmentId;
                        usr.DivisionId = userRole.ApplicationUser.DivisionId;
                        usr.JobId = userRole.ApplicationUser.JobId;
                        usr.GradeId = userRole.ApplicationUser.GradeId;
                        usr.BirthPlace = userRole.ApplicationUser.BirthPlace;
                        usr.BirthDate = userRole.ApplicationUser.BirthDate;
                        usr.EmployeeType = userRole.ApplicationUser.EmployeeType;
                        usr.SyncId = userRole.ApplicationUser.SyncId;

                        foreach (var item in toRemove)
                        {
                            _context.UserRoles.Remove(new IdentityUserRole<string>
                            {
                                RoleId = item,
                                UserId = usr.Id
                            });
                        }
                        foreach (var item in toAdd)
                        {
                            _context.UserRoles.Add(new IdentityUserRole<string>
                            {
                                RoleId = item,
                                UserId = usr.Id
                            });
                        }

                        var update = await _userManager.UpdateAsync(usr);

                        if (!update.Succeeded)
                        {
                            foreach (var error in update.Errors)
                            {
                                ModelState.AddModelError(string.Empty, error.Description);
                            }
                        }
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!UsernameExists(userRole.ApplicationUser.UserName))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                }
                else //create new
                {
                    userRole.ApplicationUser.EmailConfirmed = true;
                    var selectedRoleId = userRole.ApplicationRoles.Where(x => x.Selected).Select(x => x.Value);

                    foreach (var item in selectedRoleId)
                    {
                        _context.UserRoles.Add(new IdentityUserRole<string>
                        {
                            RoleId = item,

EOS.Web/Views/AppUsers/AddOrEdit.cshtml
@model EOS.Web.Models.UserRole
@{
    Layout = null;
}
<div class="row">
    <div class="col-md-12">
        <form asp-action="AddOrEdit" asp-route-id="@Model.ApplicationUser.Id" onsubmit="return jQueryAjaxPost(this);" autocomplete="off" enctype="multipart/form-data">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="row">
                <div class="col-md-6">
                    <h5><b>Data Karyawan</b></h5>
                    <div class="form-group">
                        <label asp-for="@Model.ApplicationUser.UserName" class="control-label">Username</label><span class="required"> *</span>
                        <input asp-for="@Model.ApplicationUser.UserName" class="form-control" />
                        <span asp-validation-for="@Model.ApplicationUser.UserName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.ApplicationUser.FullName" class="control-label">Nama Lengkap</label><span class="required"> *</span>
                        <input asp-for="@Model.ApplicationUser.FullName" class="form-control" />
                        <span asp-validation-for="@Model.ApplicationUser.FullName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.ApplicationUser.Email" class="control-label">Email</label><span class="required"> *</span>
                        <input asp-for="@Model.ApplicationUser.Email" class="form-control" />
                        <span asp-validation-for="@Model.ApplicationUser.Email" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.ApplicationUser.BirthPlace" class="control-label">Tempat Lahir</label><span class="required"> *</span>
                        <input asp-for="@Model.ApplicationUser.BirthPlace" class="form-control" />
                        <span asp-validation-for="@Model.ApplicationUser.BirthPlace" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.ApplicationUser.BirthDate" class="control-label">Tanggal Lahir</label><span class="required"> *</span>
                        <input asp-for="@Model.ApplicationUser.BirthDate" class="form-control" type="date" />
                        <span asp-validation-for="@Model.ApplicationUser.BirthDate" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <h5><b>Detail Karyawan</b></h5>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="@Model.ApplicationUser.EmployeeNumber" class="control-label">No. Karyawan</label><span class="required"> *</span>
                                <input asp-for="@Model.ApplicationUser.EmployeeNumber" class="form-control" />
                                <span asp-validation-for="@Model.ApplicationUser.EmployeeNumber" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="@Model.ApplicationUser.SyncId" class="control-label">Sync ID</label><span class="required"> *</span>
                                <input asp-for="@Model.ApplicationUser.SyncId" class="form-control" min="0" />
                                <span asp-validation-for="@Model.ApplicationUser.SyncId" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.ApplicationUser.StartJoinDate" class="control-label">Tanggal Mulai Bekerja</label><span class="required"> *</span>
                        <input asp-for="@Model.ApplicationUser.StartJoinDate" class="form-control" type="date" />
                        <span asp-validation-for="@Model.ApplicationUser.StartJoinDate" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.ApplicationUser.Section" class="control-label">Bagian</label><span class="required"> *</span>
                        <select asp-for="@Model.ApplicationUser.SectionId" asp-items="(IEnumerable<SelectListItem>)ViewBag.Section" class="form-control">
                            <option value="0">-</option>
                        </select>
                        <span asp-validation-for="@Model.ApplicationUser.SectionId" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.ApplicationUser.Department" class="control-label">Departemen</label><span class="required"> *</span>
                        <select asp-for="@Model.ApplicationUser.DepartmentId" asp-items="(IEnumerable<SelectListItem>)ViewBag.Department" class="form-control">
                            <option value="0">-</option>
                        </select>
                        <span asp-validation-for="@Model.ApplicationUser.DepartmentId" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.ApplicationUser.Division" class="control-label">Divisi</label><span class="required"> *</span>
                        <select asp-for="@Model.ApplicationUser.DivisionId" asp-items="(IEnumerable<SelectListItem>)ViewBag.Division" class="form-control">
                            <option value="0">-</option>
                        </select>
                        <span asp-validation-for="@Model.ApplicationUser.DivisionId" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.ApplicationUser.Job" class="control-label">Posisi</label><span class="required"> *</span>
                        <select asp-for="@Model.ApplicationUser.JobId" asp-items="(IEnumerable<SelectListItem>)ViewBag.Job" class="form-control">
                            <option value="0">-</option>
                        </select>
                        <span asp-validation-for="@Model.ApplicationUser.JobId" class="text-danger"></span>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="@Model.ApplicationUser.Grade" class="control-label">Grade</label><span class="required"> *</span>
                                <select asp-for="@Model.ApplicationUser.GradeId" asp-items="(IEnumerable<SelectListItem>)ViewBag.Grade" class="form-control">
                                    <option value="0">-</option>
                                </select>
                                <span asp-validation-for="@Model.ApplicationUser.GradeId" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="@Model.ApplicationUser.EmployeeType" class="control-label">Tipe</label><span class="required"> *</span>
                                <select asp-for="@Model.ApplicationUser.EmployeeType" class="form-control">
                                    <option value="">-</option>
                                    <option value="Daily">Daily</option>
                                    <option value="Shift">Shift</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-12">
                    <h5><b>Hak Akses</b></h5>
                    <hr />
                    <div class="form-group">
                        <label asp-for="@Model.ApplicationRoles" class="control-label">Role</label><span class="required"> *</span>
                        <br />
                        @for (int i = 0; i < Model.ApplicationRoles.Count; i++)
                        {
                            <input type="hidden" asp-for="@Model.ApplicationRoles[i].Value" />
                            <input asp-for="@Model.ApplicationRoles[i].Selected" /> @Model.ApplicationRoles[i].Text
                        }
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Submit" class="btn btn-primary btn-block" />
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
    

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EOS.Web/Views/AppUsers/Delete.cshtml
@model EOS.Web.Areas.Identity.Data.AppUser

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Bank</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FullName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FullName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

EOS.Web/Views/AppUsers/Index.cshtml
@model PaginatedList<EOS.Web.Areas.Identity.Data.AppUser>
@{
    ViewData["Title"] = "Karyawan";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<head>
    @section AddToHead{
        <link rel="stylesheet" href="~/datatables/DataTables-1.10.23/css/dataTables.bootstrap4.min.css" />
        <link rel="stylesheet" href="~/datatables/select.dataTables.min.css" />
        <script src="~/datatables/datatables.min.js"></script>
        <script src="~/datatables/dataTables.select.min.js"></script>
        <script src="~/moment.js/moment.min.js"></script>
        <script type="text/javascript">
            $(document).ready(function () {
                var table = $("#tbl-grid").DataTable({
                    "processing": false, // for show progress bar
                    "serverSide": true, // for process server side
                    "filter": true, // this is for disable filter (search box)
                    "orderMulti": false, // for disable multiple column at once
                    "scrollX": true,
                    "language": {
                        "lengthMenu": "Menampilkan _MENU_ baris per halaman",
                        "zeroRecords": "Data tidak ditemukan.",
                        "info": "Menampilkan halaman _PAGE_ dari _PAGES_",
                        "infoEmpty": "Data tidak ditemukan.",
                        "infoFiltered": "(Disaring dari _MAX_ baris)",
                        "search": "Pencarian :",
                        "paginate": {
                            "previous": "Sebelumnya",
                            "next": "Selanjutnya"
                        },
                        "select": {
                            "rows": {
                                _: "",
                                0: "",
                                1: "%d baris terpilih"
                            }
                        },
                    },
                    "ajax": {
                        "url": "/AppUsers/LoadData",
                        "type": "POST",
                        "datatype": "json"
                    },
                    "select": {
                        "style": "single"
                    },
                    "columnDefs": [{
                        "targets": [0],
                        "visible": false,
                        "searchable": false
                    },
                    {
                        "targets": [9],
                        "orderable": false
                    }],
                    "columns": [
                        { "data": "id", "name": "Id", "autoWidth": true },
                        {
                            data: null,
                            render: function (data, type, full, meta) {
                                //return "<a href='#' class='btn btn-info' onclick=UpdateData('" + full.sectionId + "');>Update</a> <a href='#' class='btn btn-danger' onclick=DeleteData('" + full.sectionId + "');>Hapus</a> ";
                                return "<a href='#' class='btn btn-info' data-bs-toggle='tooltip' data-bs-placement='top' title='Update Data Karyawan' onclick=UpdateData('" + full.id + "');><i class='fas fa-edit'></i></a>";
                            }
                        },
                        {
                            data: null,
                            render: function (data, type, full, meta) {
                                //return "<a href='#' class='btn btn-info' onclick=UpdateData('" + full.sectionId + "');>Update</a> <a href='#' class='btn btn-danger' onclick=DeleteData('" + full.sectionId + "');>Hapus</a> ";
                                if (full.endJoinDate == '0001-01-01T00:00:00') {
                                    return "<a href='#' class='btn btn-danger' data-bs-toggle='tooltip' data-bs-placement='top' title='Inaktif Data Karyawan' onclick=SetInactive('" + full.id + "');><i class='fas fa-user-slash'></i></a>";
                                }
                                else {
                                    return '';
                                }
                            }
                        },
                        {
                            data: null,
                            render: function (data, type, full, meta) {
                                //return "<a href='#' class='btn btn-info' onclick=UpdateData('" + full.sectionId + "');>Update</a> <a href='#' class='btn btn-danger' onclick=DeleteData('" + full.sectionId + "');>Hapus</a> ";
                                return "<a href='#' class='btn btn-warning' data-bs-toggle='tooltip' data-bs-placement='top' title='Reset Password' onclick=ResetPassword('" + full.id + "','" + full.userName + "');><i class='fas fa-key'></i></a>";
                            }
                        },
                        { "data": "fullName", "name": "FullName", "autoWidth": true },
                        { "data": "employeeNumber", "name": "EmployeeNumber", "autoWidth": true },
                        { "data": "email", "name": "Email", "autoWidth": true },
                        { "data": "phoneNumber", "name": "PhoneNumber", "autoWidth": true },
                        { "data": "birthPlace", "name": "BirthPlace", "autoWidth": true },
                        {
                            data: "birthDate", name: "BirthDate",
                            render: function (data, type, row) {
                                if (row.birthDate == '0001-01-01T00:00:00') {
                                    return '';
                                }
                                else {
                                    return moment(row.birthDate).format('DD MMM YYYY');
                                }
                            }
                        },
                        {
                            data: "startJoinDate", name:"StartJoinDate",
                            render: function (data, type, row) {
                                if (row.startJoinDate == '0001-01-01T00:00:00') {
                                    return '';
                                }
                                else {
                                    return moment(row.startJoinDate).format('DD MMM YYYY');
                                }
                            }
                        },
                        {
                            data: "endJoinDate", name:"EndJoinDate",
                            render: function (data, type, row) {
                                if (row.endJoinDate == '0001-01-01T00:00:00') {
                                    return '';
                                }
                                else {
                                    return moment(row.endJoinDate).format('DD MMM YYYY');
                                }
                            }
                        },
                    ]
                });
            }); //end document ready
            function UpdateData(userId) {
                var toSend =
                {
                    id: userId
                };
                $.ajax({
                    type: "GET",
                    contentType: "application/json; charset=utf-8",
                    url: "/AppUsers/AddOrEdit",
                    data: toSend,
                    success: function (res) {
                        $("#form-modal-lg .modal-body").html(res);
                        $("#form-modal-lg .modal-title").html("Update Data Karyawan");
                        $("#form-modal-lg").modal('show');
                    },
                    error: function (res) {
                        console.log(res);
                    }
                })
            };
            function DeleteData(userId) {
                if (confirm('Apakah anda yakin akan menghapus data ini ?')) {
                    var toSend =
                    {
                        id: userId
                    };
                    $.ajax({
                        type: 'POST',
                        url: '/AppUsers/Delete',
                        data: toSend,
                        success: function (res) {
                            $.notify('Data berhasil dihapus', { globalPosition: 'bottom right', className: 'success', width: '150px' });
                            oTable = $('#tbl-grid').DataTable();
                            oTable.ajax.reload(null, false);
                        },
                        error: function (err) {
                            console.log(err);
                        }
                    })
                }
            };
            function ResetPassword(userId, userName) {
                if (confirm('Apakah anda yakin akan reset password user ' + userName + ' ini?')) {
                    var toSend = {
                        id: userId
                    };
                    $.ajax({
                        type: 'POST',
                        url: '/AppUsers/ResetPassword',
                        data: toSend,
                        success: function (res) {
                            $.notify('Reset password berhasil', { globalPosition: 'bottom right', className: 'success', width: '150px' });
                            oTable = $('#tbl-grid').DataTable();
                            oTable.ajax.reload(null, false);
                        },
                        error: function (err) {
                            console.log(err);
                        }
                    })
                }
            };
            function SetInactive(userId) {
                var toSend =
                {
                    id: userId
                };
                $.ajax({
                    type: "GET",
                    contentType: "application/json; charset=utf-8",
                    url: "/AppUsers/SetInactive",
                    data: toSend,
                    success: function (res) {
                        $("#form-modal-lg .modal-body").html(res);
                        $("#form-modal-lg .modal-title").html("Non aktifkan Karyawan");
                        $("#form-modal-lg").modal('show');
                    },
                    error: function (res) {
                        console.log(res);
                    }
                })
            };
        </script>
    }
</head>
<div class="row">
    <div class="col-md-7">
        <h1><i class="fas fa-user-alt text-primary"></i> Karyawan</h1>
    </div>
    <div class="col-md-5 text-right">
        <a onclick="showInPopupLg('@Url.Action("AddOrEdit","AppUsers",new { id = string.Empty },Context.Request.Scheme)', 'Tambah Baru')" class="btn btn-success btn-sm text-white"><i class="fas fa-plus-circle"></i> Tambah Baru</a>
    </div>
    <div class="col-md-12">
        <div id="view-all">
            @await Html.PartialAsync("_ViewAll", Model)
        </div>
    </div>
</div>