EOS.Web/Models/PaidLeavePeriod.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using EOS.Web.Areas.Identity.Data;

namespace EOS.Web.Models
{
    public class PaidLeavePeriod
    {
        //private AppUser _user;

        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Periode wajib diisi")]
        [Display(Name = "Periode")]
        public string PeriodName { get; set; }

        [Display(Name = "Start Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = false, DataFormatString = "{0:MM/dd/yyyy}")]
        public DateTime StartDate { get; set; }

        [Display(Name = "End Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = false, DataFormatString = "{0:MM/dd/yyyy}")]
        public DateTime EndDate { get; set; }

        public double Value { get; set; }

        public int Status { get; set; }

        public AppUser User { get; set; }

        public string UserId { get; set; }

        //helper
        public string StatusString
        {
            get
            {
                if (Status == 1)
                {
                    return "Aktif";
                }
                else
                {
                    return "Inaktif";
                }
            }
        }
    }
}

EOS.Web/Controllers/PaidLeavePeriodController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Dynamic.Core;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EOS.Web.Data;
using EOS.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace EOS.Web.Controllers
{
    public class PaidLeavePeriodController : Controller
    {
        private readonly EOSContext _context;

        public PaidLeavePeriodController(EOSContext context)
        {
            _context = context;
        }

        // GET: PaidLeavePeriod
        [Authorize]
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult LoadData()
        {
            try
            {
                var draw = HttpContext.Request.Form["draw"].FirstOrDefault();
                var start = Request.Form["start"].FirstOrDefault();// Skip number of Rows count  
                var length = Request.Form["length"].FirstOrDefault(); // Paging Length 10,20  
                var sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault(); // Sort Column Name  
                var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();// Sort Column Direction (asc, desc)  
                var searchValue = Request.Form["search[value]"].FirstOrDefault(); // Search Value from (Search box)  
                int pageSize = length != null ? Convert.ToInt32(length) : 0; //Paging Size (10, 20, 50,100)  
                int skip = start != null ? Convert.ToInt32(start) : 0;
                int recordsTotal = 0;

                // getting all data  
                var paidLeavePeriod = (from p in _context.PaidLeavePeriod join u in _context.AppUsers on p.UserId equals u.Id
                            select new { p.Id, p.PeriodName, p.StartDate, p.EndDate, u.FullName, p.Value, p.StatusString });
                //Sorting  
                if (!(string.IsNullOrEmpty(sortColumn) && string.IsNullOrEmpty(sortColumnDirection)))
                {
                    paidLeavePeriod = paidLeavePeriod.OrderBy(sortColumn + " " + sortColumnDirection);
                }
                //Search  
                if (!string.IsNullOrEmpty(searchValue))
                {
                    paidLeavePeriod = paidLeavePeriod.Where(m => m.PeriodName.Contains(searchValue) || m.FullName.Contains(searchValue));
                }

                //total number of rows counts   
                recordsTotal = paidLeavePeriod.Count();
                //Paging   
                var data = paidLeavePeriod.Skip(skip).Take(pageSize).ToList();
                //Returning Json Data  
                return Json(new { draw = draw, recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = data });
            }
            catch (Exception)
            {
                throw;
            }
        }

        // GET: PaidLeavePeriod/AddOrEdit
        [NoDirectAccess]
        public async Task<IActionResult> AddOrEdit(int id = 0)
        {
            if (id == 0)//flagged as insert
            {
                PopulateUser();
                return View(new PaidLeavePeriod());
            }
            else
            {
                var paidLeavePeriod = await _context.PaidLeavePeriod.FindAsync(id);
                PopulateUser(paidLeavePeriod.User);
                if (paidLeavePeriod == null)
                {
                    return NotFound();
                }
                return View(paidLeavePeriod);
            }
        }

        // POST: Banks/AddOrEdit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOrEdit(int id, [Bind("Id,UserId,PeriodName,StartDate,EndDate,Value,Status")] PaidLeavePeriod paidLeavePeriod)
        {
            if (ModelState.IsValid)
            {
                if (id == 0) //add new
                {
                    _context.Add(paidLeavePeriod);
                    await _context.SaveChangesAsync();
                }
                else //update
                {
                    try
                    {
                        _context.Update(paidLeavePeriod);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!PeriodExists(paidLeavePeriod.Id))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                }
                return Json(new { isValid = true, html = Helper.RenderRazorViewString(this, "_ViewAll", _context.PaidLeavePeriod.ToList()) });
            }
            else {
                var errors = ModelState.Values.SelectMany(v => v.Errors);
                PopulateUser();
                return Json(new { isValid = false, html = Helper.RenderRazorViewString(this, "AddOrEdit", paidLeavePeriod) });
            }
        }

        private bool PeriodExists(int id)
        {
            return _context.PaidLeavePeriod.Any(e => e.Id == id);
        }

        // POST: PaidLeavePeriod/Delete/5
        [HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var paidLeavePeriod = await _context.PaidLeavePeriod.FindAsync(id);
            _context.PaidLeavePeriod.Remove(paidLeavePeriod);
            await _context.SaveChangesAsync();
            return Json(new { html = Helper.RenderRazorViewString(this, "_ViewAll", _context.PaidLeavePeriod.ToList()) });
        }

        private void PopulateUser(object selectedType = null)
        {
            var userQuery = from d in _context.AppUsers
                            where d.EndJoinDate.Equals(DateTime.MinValue)
                            orderby d.Id
                            select d;
            List<SelectListItem> items = new SelectList(userQuery, "Id", "FullName", selectedType).ToList();
            ViewBag.User = new SelectList(items, "Value", "Text");
        }

        public JsonResult GetPeriodUser(string id)
        {
            var period = _context.PaidLeavePeriod.Where(p => p.UserId == id && p.Status.Equals(1));
            return new JsonResult(period);
        }
    }
}

EOS.Web/Views/PaidLeavePeriod/AddOrEdit.cshtml
@model EOS.Web.Models.PaidLeavePeriod

@{
    ViewData["Title"] = "Edit";
    Layout = null;
}

<div class="row">
    <div class="col-md-12">
        <form asp-action="AddOrEdit" asp-route-id="@Model.Id" onsubmit="return jQueryAjaxPost(this);" autocomplete="off">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" id="txtId" />
            <div class="form-group">
                <label asp-for="PeriodName" class="control-label"></label><span class="required"> *</span>
                <input asp-for="PeriodName" class="form-control" />
                <span asp-validation-for="PeriodName" class="text-danger"></span>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label asp-for="StartDate" class="control-label"></label><span class="required"> *</span>
                    <input asp-for="StartDate" class="form-control" type="date" min="2020-01-01" />
                    <span asp-validation-for="StartDate" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6">
                    <label asp-for="EndDate" class="control-label"></label><span class="required"> *</span>
                    <input asp-for="EndDate" class="form-control" type="date" min="2020-01-01" />
                    <span asp-validation-for="EndDate" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="@Model.UserId" class="control-label">Tipe</label><span class="required"> *</span>
                <select asp-for="@Model.UserId" asp-items="(IEnumerable<SelectListItem>)ViewBag.User" id="txtUserId" class="form-control">
                    <option value="0">- Pilih Employee -</option>
                </select>
                <span asp-validation-for="@Model.UserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Value" class="control-label"></label><span class="required"> *</span>
                <input asp-for="Value" class="form-control" />
                <span asp-validation-for="Value" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label><span class="required"> *</span>
                <select asp-for="Status" class="form-control">
                    <option value=""></option>
                    <option value="0">Inaktif</option>
                    <option value="1">Aktif</option>
                </select>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Submit" class="btn btn-primary btn-block" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EOS.Web/Views/PaidLeavePeriod/Delete.cshtml
@model EOS.Web.Models.PaidLeavePeriod 

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Bank</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PeriodName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PeriodName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

EOS.Web/Views/PaidLeavePeriod/Index.cshtml
@model EOS.Web.Models.PaidLeavePeriod
@{
    ViewData["Title"] = "Periode Cuti";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<head>
    @section AddToHead{
        <link rel="stylesheet" href="~/datatables/DataTables-1.10.23/css/dataTables.bootstrap4.min.css" />
        <script src="~/datatables/datatables.min.js"></script>
        <script src="~/moment.js/moment.min.js"></script>
        <script type="text/javascript">
            $(document).ready(function () {
                $("#tbl-grid").DataTable({
                    "processing": false, // for show progress bar
                    "serverSide": true, // for process server side
                    "filter": true, // this is for disable filter (search box)
                    "orderMulti": false, // for disable multiple column at once
                    "language": {
                        "lengthMenu": "Menampilkan _MENU_ baris per halaman",
                        "zeroRecords": "Data tidak ditemukan.",
                        "info": "Menampilkan halaman _PAGE_ dari _PAGES_",
                        "infoEmpty": "Data tidak ditemukan.",
                        "infoFiltered": "(Disaring dari _MAX_ baris)",
                        "search": "Pencarian :",
                        "paginate": {
                            "previous": "Sebelumnya",
                            "next": "Selanjutnya"
                        }
                    },
                    "ajax": {
                        "url": "/PaidLeavePeriod/LoadData",
                        "type": "POST",
                        "datatype": "json"
                    },

                    "columnDefs": [{
                        "targets": [0],
                        "visible": false,
                        "searchable": false
                    }],
                    "columns": [
                        { "data": "id", "name": "Id", "autoWidth": true },
                        {
                            data: null,
                            render: function (data, type, full, meta) {
                                return "<a href='#' class='btn btn-info' onclick=UpdateData('" + full.id + "');>Update</a>"; // <a href='#' class='btn btn-danger' onclick=DeleteData('" + full.id + "');>Hapus</a>
                            }
                        },
                        { "data": "periodName", "name": "PeriodName", "autoWidth": true },
                        { "data": "fullName", "name": "fullName", "autoWidth": true },
                        {
                            data: "startDate", name:"StartDate",
                            render: function (data, type, row) {
                                return moment(row.startDate).format('DD MMM YYYY');
                            }
                        },
                        {
                            data: "endDate", name:"EndDate",
                            render: function (data, type, row) {
                                return moment(row.endDate).format('DD MMM YYYY');
                            }
                        },
                        { "data": "value", "name": "Value", "autoWidth": true },
                        { "data": "statusString", "name": "StatusString", "autoWidth": true },
                    ]
                });

            }); //end document ready
            function UpdateData(id) {
                var toSend =
                {
                    id: id
                };
                $.ajax({
                    type: "GET",
                    contentType: "application/json; charset=utf-8",
                    url: "/PaidLeavePeriod/AddOrEdit",
                    data: toSend,
                    success: function (res) {
                        $("#form-modal .modal-body").html(res);
                        $("#form-modal .modal-title").html("Ubah");
                        $("#form-modal").modal('show');
                    },
                    error: function (res) {
                        console.log(res);
                    }
                })
            };
            function DeleteData(id) {
                if (confirm('Apakah anda yakin akan menghapus data ini ?')) {
                    var toSend =
                    {
                        id: id
                    };
                    $.ajax({
                        type: 'POST',
                        url: '/PaidLeavePeriod/Delete',
                        data: toSend,
                        success: function (res) {
                            $.notify('Data berhasil dihapus', { globalPosition: 'bottom right', className: 'success' });
                            oTable = $('#tbl-grid').DataTable();
                            oTable.ajax.reload(null, false);
                        },
                        error: function (err) {
                            console.log(err);
                        }
                    })
                }
            }
        </script>
    }
</head>
<div class="row">
    <div class="col-md-7">
        <h1><i class="fas fa-bookmark text-primary"></i> Periode Cuti</h1>
    </div>
    <div class="col-md-5 text-right">
        <a onclick="showInPopup('@Url.Action("AddOrEdit","PaidLeavePeriod",new { id = 0 },Context.Request.Scheme)', 'Tambah Baru')" class="btn btn-success btn-sm text-white"><i class="fas fa-plus-circle"></i> Tambah Baru</a>
    </div>
    <div class="col-md-12">
        <div id="view-all">
            @await Html.PartialAsync("_ViewAll", Model)
        </div>
    </div>
</div>

EOS.Web/Views/PaidLeavePeriod/_ViewAll.cshtml
<div class="table-responsive">
    <table class="table table-bordered table-striped table-sm table-hover display" id="tbl-grid" style="width:100%">
        <thead class="">
            <tr>
                <th>Id</th>
                <th class="icon-td-1"></th>
                <th>Periode</th>
                <th>Nama</th>
                <th>Tanggal Mulai</th>
                <th>Tanggal Selesai</th>
                <th>Jumlah</th>
                <th>Status</th>
                
            </tr>
        </thead>
    </table>
</div>