EOS.Web/Controllers/PaidLeaveByHrController.cs
using System;
using System.Collections.Generic;
using System.Text;
using System.Linq;
using System.Linq.Dynamic.Core;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EOS.Web.Data;
using EOS.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using EOS.Web.Areas.Identity.Data;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Hosting;
using System.Security.Claims;
using EOS.Web.Services;

namespace EOS.Web.Controllers
{
    public class PaidLeaveByHrController : Controller
    {
        private readonly EOSContext _context;

        public PaidLeaveByHrController(EOSContext context)
        {
            _context = context;
        }

        [Authorize]
        public ActionResult Index()
        {
            var emp = _context.AppUsers.Where(p => p.EndJoinDate != null);
            ViewBag.Employee = emp.ToList();
            return View();
        }

        public IActionResult LoadData()
        {
            try
            {
                var draw = HttpContext.Request.Form["draw"].FirstOrDefault();
                var start = Request.Form["start"].FirstOrDefault();// Skip number of Rows count  
                var length = Request.Form["length"].FirstOrDefault(); // Paging Length 10,20  
                var sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault(); // Sort Column Name  
                var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();// Sort Column Direction (asc, desc)  
                var searchValue = Request.Form["search[value]"].FirstOrDefault(); // Search Value from (Search box)  
                int pageSize = length != null ? Convert.ToInt32(length) : 0; //Paging Size (10, 20, 50,100)  
                int skip = start != null ? Convert.ToInt32(start) : 0;
                int recordsTotal = 0;

                // getting all data  
                var vrl = (from v in _context.ViewPaidLeaveDetails
                           select v);
                //Sorting  
                if (!(string.IsNullOrEmpty(sortColumn) && string.IsNullOrEmpty(sortColumnDirection)))
                {
                    vrl = vrl.OrderBy(sortColumn + " " + sortColumnDirection);
                }
                //Search  
                if (!string.IsNullOrEmpty(searchValue))
                {
                    vrl = vrl.Where(v => v.FullName.Contains(searchValue) || v.PeriodName.Contains(searchValue));
                }

                //total number of rows counts   
                recordsTotal = vrl.Count();
                //Paging   
                var data = vrl.Skip(skip).Take(pageSize).ToList();
                //Returning Json Data  
                return Json(new { draw = draw, recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = data });
            }
            catch (Exception)
            {
                throw;
            }
        }

        // GET: PaidLeaves/AddOrEdit
        [NoDirectAccess]
        public async Task<IActionResult> AddOrEdit(int id = 0)
        {
            if (id == 0)//flagged as insert
            {
                var userId = this.User.FindFirst(ClaimTypes.NameIdentifier);
                //tipe
                ViewBag.Type = _context.Type.ToList();
                //populate
                PopulateUser();
                return View(new PaidLeave());
            }
            else
            {
                var paidLeave = await _context.PaidLeave.FindAsync(id);
                PopulateUser(paidLeave.Period);
                if (paidLeave == null)
                {
                    return NotFound();
                }
                return View(paidLeave);
            }
        }

        private void PopulateUser(object selectedType = null)
        {
            //var userId = this.User.FindFirst(ClaimTypes.NameIdentifier);
            var typeQuery = from d in _context.AppUsers
                            where d.EndJoinDate.Equals(DateTime.MinValue)
                            orderby d.Id
                            select d;
            List<SelectListItem> items = new SelectList(typeQuery, "Id", "FullName", selectedType).ToList();
            ViewBag.Employee = new SelectList(items, "Value", "Text");
        }

        public JsonResult GetPeriodUser(string id)
        {
            var period = _context.PaidLeavePeriod.Where(p => p.UserId == id && p.Status != 1);
            return new JsonResult(period);
        }

    }
}

EOS.Web/Views/PaidLeaveByHr/AddOrEdit.cshtml
@model EOS.Web.Models.PaidLeave
@{
    Layout = null;
}
<script type="text/javascript">
    $(document).ready(function () {
        $('#txtRequestor').change(function () {
            var e = $('#txtRequestor').val();
            var obj = { id: e };
            if (e != 0) {
                $.ajax({
                    type: 'GET',
                    url: "@Url.Action("GetPeriodUser", "PaidLeavePeriod")",
                    data: obj,
                    success: function (res) {
                        $('#txtPeriod').empty();
                        var max = res.length;
                        $('#txtPeriod').append('<option value="0">- Pilih Period Cuti -</option>');
                        for (i = 0; i < max; i++) {
                            $('#txtPeriod').append('<option value='+ res[i].id +'>'+ res[i].periodName +'</option>');
                        }
                    }
                });
            }
        });
        $('#txtPeriod').change(function () {
            var p = $('#txtPeriod').val();
            var obj = { period: p };
            if (p != 0) {
                $.ajax({
                    type: 'GET',
                    url: "@Url.Action("GetRemainingLeaves","PaidLeaves")",
                    data: obj,
                    success: function (res) {
                        if (res[0].leaveAllowance) {
                            $('#txtTotalLeave').text('Total Cuti :' + res[0].leaveAllowance + ' Hari');
                            $('#txtRemainingLeave').text('Sisa Cuti :' + res[0].remainingLeave + ' Hari');
                        }
                        else {
                            $('#txtTotalLeave').text('Total Cuti :' + res[0].value + ' Hari');
                            $('#txtRemainingLeave').text('Sisa Cuti :' + res[0].value + ' Hari');
                        }
                    }
                });
            }
            else {
                $('#txtTotalLeave').text('Total Cuti : - Hari');
                $('#txtRemainingLeave').text('Sisa Cuti : - Hari');
            }
        });
        $("#txtStartDate, #txtStartFrom, #txtEndTo").change(function () {
            var start = $('#txtStartFrom').val();
            var end = $('#txtEndTo').val();
            if ((end - start) <= 4) {
                $('#txtValue').val(0.5);
                $('#txtCurrentValue').text('Pengajuan Izin :' + 0.5 + ' Hari');
            }
            else {
                $('#txtValue').val(1);
                $('#txtCurrentValue').text('Pengajuan Izin :' + 1 + ' Hari');
            }
        });
    });
</script>
<div class="row">
    <div class="col-md-12">
        <form asp-action="AddOrEdit" asp-route-id="@Model.PaidLeaveId" onsubmit="return jQueryAjaxPost(this);" autocomplete="off">
            <div asp-validation-summary="All" class="text-danger"></div>
            <input type="hidden" asp-for="PaidLeaveId" />
            <input type="hidden" asp-for="Value" id="txtValue" />
            <div class="form-row">
                <div class="form-group col-md-4">
                    <label id="txtTotalLeave" class="control-label font-weight-bold">Total Cuti :<br />- Hari</label>
                </div>
                <div class="form-group col-md-4">
                    <label id="txtRemainingLeave" class="control-label font-weight-bold">Sisa Cuti :<br />- Hari</label>
                </div>
                <div class="form-group col-md-4">
                    <label id="txtCurrentValue" class="control-label font-weight-bold">Pengajuan Cuti :<br />- Hari</label>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-12">
                    <label asp-for="@Model.RequestorId" class="control-label">Karyawan</label><span class="required"> *</span>
                    <select asp-for="@Model.RequestorId" asp-items="(IEnumerable<SelectListItem>)ViewBag.Employee" id="txtRequestor" class="form-control">
                        <option value="0">- Pilih Employee -</option>
                    </select>
                    <span asp-validation-for="@Model.RequestorId" class="text-danger"></span>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label asp-for="@Model.StartDate" class="control-label"></label><span class="required"> *</span>
                    <input asp-for="@Model.StartDate" id="txtStartDate" type="date" asp-format="{0:dd/MM/yyyy}" class="datepicker form-control" value="@Model.StartDate.ToString("dd/MM/yyyy")" min="2021-01-01" />
                    <span asp-validation-for="@Model.StartDate" class="text-danger"></span>
                </div>
                <div class="form-group col-md-3">
                    <label class="control-label">Mulai Jam</label><span class="required"></span>
                    <select name="From" id="txtStartFrom" class="form-control">
                        <option value="0">0</option>
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                        <option value="6">6</option>
                        <option value="7">7</option>
                        <option value="8">8</option>
                        <option value="9">9</option>
                        <option value="10">10</option>
                        <option value="11">11</option>
                        <option value="12">12</option>
                        <option value="13">13</option>
                        <option value="14">14</option>
                        <option value="15">15</option>
                        <option value="16">16</option>
                        <option value="17">17</option>
                        <option value="18">18</option>
                        <option value="19">19</option>
                        <option value="20">20</option>
                        <option value="21">21</option>
                        <option value="22">22</option>
                        <option value="23">23</option>
                    </select>
                </div>
                <div class="form-group col-md-3">
                    <label class="control-label">Sampai Jam</label><span class="required"></span>
                    <select name="To" id="txtEndTo" class="form-control">
                        <option value="0">0</option>
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                        <option value="6">6</option>
                        <option value="7">7</option>
                        <option value="8">8</option>
                        <option value="9">9</option>
                        <option value="10">10</option>
                        <option value="11">11</option>
                        <option value="12">12</option>
                        <option value="13">13</option>
                        <option value="14">14</option>
                        <option value="15">15</option>
                        <option value="16">16</option>
                        <option value="17">17</option>
                        <option value="18">18</option>
                        <option value="19">19</option>
                        <option value="20">20</option>
                        <option value="21">21</option>
                        <option value="22">22</option>
                        <option value="23">23</option>
                    </select>
                </div>
                @*<div class="form-group col-md-6">
            <label asp-for="@Model.EndDate" class="control-label"></label><span class="required"> *</span>
            <input asp-for="@Model.EndDate" id="txtEndDate" type="date" placeholder="dd-mm-yyyy" asp-format="{0:dd/MM/yyyy}" class="datepicker form-control" value="@Model.EndDate.ToString("dd/MM/yyyy")" min="2021-01-01" />
            <span asp-validation-for="@Model.EndDate" class="text-danger"></span>
        </div>*@
            </div>
            <div class="form-group">
                <label asp-for="@Model.PeriodId" class="control-label">Periode</label><span class="required"> *</span>
                <select asp-for="@Model.PeriodId" asp-items="(IEnumerable<SelectListItem>)ViewBag.Period" id="txtPeriod" class="form-control">
                    <option value="0">- Pilih Period Cuti -</option>
                </select>
                <span asp-validation-for="@Model.PeriodId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Remarks" title="Keterangan" class="control-label"></label><span class="required"> *</span>
                <textarea asp-for="Remarks" type="text" rows="3" class="form-control"></textarea>
                <span asp-validation-for="Remarks" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Ajukan Izin" class="btn btn-primary btn-block" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EOS.Web/Views/PaidLeaveByHr/Index.cshtml
@model EOS.Web.Models.PaidLeave
@{
    ViewData["Title"] = "Input Cuti / Izin Karyawan";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<head>
    @section AddToHead{
        <link rel="stylesheet" href="~/datatables/DataTables-1.10.23/css/dataTables.bootstrap4.min.css" />
        <script src="~/datatables/datatables.min.js"></script>
        <script src="~/moment.js/moment.min.js"></script>
        <script type="text/javascript">
            $(document).ready(function () {
                $("#tbl-grid").DataTable({
                    "processing": false, // for show progress bar
                    "serverSide": true, // for process server side
                    "filter": true, // this is for disable filter (search box)
                    "orderMulti": false, // for disable multiple column at once
                    "language": {
                        "lengthMenu": "Menampilkan _MENU_ baris per halaman",
                        "zeroRecords": "Data tidak ditemukan.",
                        "info": "Menampilkan halaman _PAGE_ dari _PAGES_",
                        "infoEmpty": "Data tidak ditemukan.",
                        "infoFiltered": "(Disaring dari _MAX_ baris)",
                        "search": "Pencarian :",
                        "paginate": {
                            "previous": "Sebelumnya",
                            "next": "Selanjutnya"
                        }
                    },
                    "ajax": {
                        "url": "/PaidLeaveByHr/LoadData",
                        "type": "POST",
                        "datatype": "json"
                    },

                    "columnDefs": [{
                        "targets": [0], //hide id
                        "visible": false,
                        "searchable": false
                    },
                    {
                        "targets": [1],
                        "orderable": false
                    }],
                    "columns": [
                        { "data": "paidLeaveId", "name": "PaidLeaveId", "autoWidth": true },
                        {
                            data: null,
                            render: function (data, type, full, meta) {
                                return "<a href='#' class='btn btn-info' onclick=ShowDetail('" + full.paidLeaveId + "');><i class='fas fa-search'></i></a>";
                            }
                        },
                        {
                            data: "startDate",
                            render: function (data, type, row) {
                                return moment(row.startDate).format('DD MMM YYYY');
                            }
                        },
                        {
                            data: "endDate",
                            render: function (data, type, row) {
                                return moment(row.endDate).format('DD MMM YYYY');
                            }
                        },
                        { "data": "fullName", "name": "Full Name", "autoWidth": true },
                        { "data": "remarks", "name": "Remarks", "autoWidth": true },
                        { "data": "status", "name": "Status", "autoWidth": true },
                    ],
                });

            }); //end document ready
            function UpdateData(paidLeaveId) {
                var toSend =
                {
                    id: paidLeaveId
                };
                $.ajax({
                    type: "GET",
                    contentType: "application/json; charset=utf-8",
                    url: "/Permit/AddOrEdit",
                    data: toSend,
                    success: function (res) {
                        $("#form-modal .modal-body").html(res);
                        $("#form-modal .modal-title").html("Ubah");
                        $("#form-modal").modal('show');
                    },
                    error: function (res) {
                        console.log(res);
                    }
                })
            };
            function ShowDetail(paidLeaveId) {
                var toSend =
                {
                    id: paidLeaveId
                };
                $.ajax({
                    type: "GET",
                    contentType: "application/json; charset=utf-8",
                    url: "/Permit/Details",
                    data: toSend,
                    success: function (res) {
                        $("#form-modal .modal-body").html(res.html);
                        $("#form-modal .modal-title").html("Detail Pengajuan Cuti");
                        $("#form-modal").modal('show');
                    },
                    error: function (res) {
                        console.log(res);
                    }
                })
            };
            function DeleteData(bankId) {
                if (confirm('Apakah anda yakin akan menghapus data ini ?')) {
                    var toSend =
                    {
                        id: bankId
                    };
                    $.ajax({
                        type: 'POST',
                        url: '/Permit/Delete',
                        data: toSend,
                        success: function (res) {
                            $.notify('Data berhasil dihapus', { globalPosition: 'bottom right', className: 'success' });
                            oTable = $('#tbl-grid').DataTable();
                            oTable.ajax.reload(null, false);
                        },
                        error: function (err) {
                            console.log(err);
                        }
                    })
                }
            }
        </script>
    }
</head>
<div class="row">
    <div class="col-md-7">
        <h1><i class="fas fa-user-injured text-primary"></i> Input Izin / Cuti</h1>
    </div>
    <div class="col-md-5 text-right">

        <a onclick="showInPopup('@Url.Action("AddOrEdit", "PaidLeaveByHr", new { id = 0 }, Context.Request.Scheme)', 'Input Cuti / Izin Karyawan')" class="btn btn-success btn-sm text-white"><i class="fas fa-plus-circle"></i> Input Cuti / Izin Karyawan</a>
    </div>
    <div class="col-md-12">
        <div id="view-all">
            @await Html.PartialAsync("_ViewAll", Model)
        </div>
    </div>
</div>

EOS.Web/Views/PaidLeaveByHr/_ViewAll.cshtml
<div class="table-responsive">
    <table class="table table-bordered table-striped table-sm table-hover display" id="tbl-grid" style="width:100%">
        <thead class="">
            <tr>
                <th>PaidLeaveId</th>
                <th class="icon-td-2"></th>
                <th>Tanggal Mulai</th>
                <th>Tanggal Selesai</th>
                <th>Requestor</th>
                <th>Deskripsi</th>
                <th>Status</th>
                @*<th class="icon-td"></th>*@
            </tr>
        </thead>
    </table>
</div>