EOS.Web/Controllers/PermitController.cs
using System;
using System.Collections.Generic;
using System.Text;
using System.Linq;
using System.Linq.Dynamic.Core;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EOS.Web.Data;
using EOS.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using EOS.Web.Areas.Identity.Data;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Hosting;
using System.Security.Claims;
using EOS.Web.Services;

namespace EOS.Web.Controllers
{
    public class PermitController : Controller
    {
        private readonly EOSContext _context;
        private readonly UserManager<AppUser> _userManager;
        private readonly IMailer _mailer;
        private readonly IWebHostEnvironment _hostingEnvironment;

        public PermitController(EOSContext context, UserManager<AppUser> userManager, IMailer mailer, IWebHostEnvironment env)
        {
            _context = context;
            _userManager = userManager;
            _mailer = mailer;
            _hostingEnvironment = env;
        }

        // GET: Permit
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }

        public IActionResult LoadData()
        {
            try
            {
                var draw = HttpContext.Request.Form["draw"].FirstOrDefault();
                var start = Request.Form["start"].FirstOrDefault();// Skip number of Rows count  
                var length = Request.Form["length"].FirstOrDefault(); // Paging Length 10,20  
                var sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault(); // Sort Column Name  
                var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();// Sort Column Direction (asc, desc)  
                var searchValue = Request.Form["search[value]"].FirstOrDefault(); // Search Value from (Search box)  
                int pageSize = length != null ? Convert.ToInt32(length) : 0; //Paging Size (10, 20, 50,100)  
                int skip = start != null ? Convert.ToInt32(start) : 0;
                int recordsTotal = 0;

                // getting all data 
                var userId = this.User.FindFirst(ClaimTypes.NameIdentifier);
                var paidLeave = (from p in _context.PaidLeave
                                 join u in _context.AppUsers on p.RequestorId equals u.Id
                                 join t in _context.Type on p.TypeId equals t.Id
                                 where (p.Requestor.Id.Equals(userId.Value) && p.SubmissionType == "Izin")
                                 select new { p.PaidLeaveId, p.StartDate, p.EndDate, p.TypeId, t.PaidLeaveName, p.Remarks, p.Status, p.RequestorId, p.RequestDate, p.Value, p.FirstApprover, p.FirstApproverResponse, p.FirstApproverTimestamp, p.SecondApprover, p.SecondApproverResponse, p.SecondApproverTimestamp, u.FullName });
                //Sorting  
                if (!(string.IsNullOrEmpty(sortColumn) && string.IsNullOrEmpty(sortColumnDirection)))
                {
                    paidLeave = paidLeave.OrderBy(sortColumn + " " + sortColumnDirection);
                }
                //Search  
                if (!string.IsNullOrEmpty(searchValue))
                {
                    paidLeave = paidLeave.Where(p => p.Remarks.Contains(searchValue) || p.Status.Contains(searchValue) || p.FullName.Contains(searchValue));
                }

                //total number of rows counts   
                recordsTotal = paidLeave.Count();
                //Paging   
                var data = paidLeave.Skip(skip).Take(pageSize).ToList();
                //Returning Json Data  
                return Json(new { draw = draw, recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = data });
            }
            catch (Exception)
            {
                throw;
            }
        }

        // GET: PaidLeaves/AddOrEdit
        [NoDirectAccess]
        public async Task<IActionResult> AddOrEdit(int id = 0)
        {
            if (id == 0)//flagged as insert
            {
                var userId = this.User.FindFirst(ClaimTypes.NameIdentifier);
                //tipe
                ViewBag.Type = _context.Type.ToList();
                //populate
                //PopulateTypeDropDownList();
                PopulatePaidLeavePeriod();
                return View(new PaidLeave());
            }
            else
            {
                var paidLeave = await _context.PaidLeave.FindAsync(id);
                //PopulateTypeDropDownList(paidLeave.Type);
                PopulatePaidLeavePeriod(paidLeave.Period);
                if (paidLeave == null)
                {
                    return NotFound();
                }
                return View(paidLeave);
            }
        }

        private void PopulatePaidLeavePeriod(object selectedType = null)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier);
            var typeQuery = from d in _context.PaidLeavePeriod
                            where d.UserId.Equals(userId.Value) && d.Status.Equals(1) && d.EndDate > DateTime.Today
                            orderby d.Id
                            select d;
            List<SelectListItem> items = new SelectList(typeQuery, "Id", "PeriodName", selectedType).ToList();
            ViewBag.Period = new SelectList(items, "Value", "Text");
        }

        // POST: PaidLeaves/AddOrEdit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOrEdit(int id, [Bind("StartDate,From,To,PeriodId,Remarks,Value")] PaidLeave paidLeave, string from, string to)
        {
            if (ModelState.IsValid && Validation(paidLeave, from, to))
            {
                if (id == 0) //add new cuti
                {
                    DateTime permitStart = paidLeave.StartDate;
                    DateTime permitEnd = paidLeave.StartDate;
                    paidLeave.RequestDate = DateTime.Now;
                    paidLeave.Status = "Submitted";
                    paidLeave.SubmissionType = "Izin";
                    paidLeave.TypeId = 16;
                    paidLeave.StartDate = permitStart.AddHours(Convert.ToDouble(from));
                    paidLeave.EndDate = permitEnd.AddHours(Convert.ToDouble(to));
                    AppUser applicationUser = await _userManager.GetUserAsync(User);
                    paidLeave.Requestor = applicationUser;
                    //check role first
                    var checkRoleApprover = await _userManager.IsInRoleAsync(applicationUser, "Approver");
                    if (checkRoleApprover)
                    {
                        //if bod, auto completed
                        var checkBoD = await _userManager.IsInRoleAsync(applicationUser, "BoD");
                        var isDepartmentHead = await _context.Department.Where(x => x.DepartmentHead == applicationUser.Email).FirstOrDefaultAsync();
                        var isSectionHead = await _context.Section.Where(x => x.SectionHead == applicationUser.Email).FirstOrDefaultAsync();
                        if (checkBoD) //is BoD, auto completed
                        {
                            DateTime now = DateTime.Now;
                            paidLeave.Status = "Completed";
                            paidLeave.FirstApprover = applicationUser.Email;
                            paidLeave.FirstApproverResponse = "Approve";
                            paidLeave.FirstApproverTimestamp = now;
                            paidLeave.SecondApprover = applicationUser.Email;
                            paidLeave.SecondApproverResponse = "Approve";
                            paidLeave.SecondApproverTimestamp = now;
                            _context.Add(paidLeave);
                            await _context.SaveChangesAsync();
                            return Json(new { isValid = true, html = Helper.RenderRazorViewString(this, "_ViewAll", _context.PaidLeave.ToList()) });
                        }
                        //if manager, need approval bod
                        else if (isDepartmentHead != null) //manager, need BoD Approval
                        {
                            //find bod
                            var bod = await (from user in _context.AppUsers
                                             join userRole in _context.UserRoles
                                             on user.Id equals userRole.UserId
                                             join role in _context.Roles
                                             on userRole.RoleId equals role.Id
                                             where role.Name == "BoD"
                                             select user).ToListAsync();
                            List<string> emailList = new List<string>();
                            foreach (AppUser b in bod)
                            {
                                emailList.Add(b.Email);
                            }
                            string email = string.Join(",", emailList);
                            paidLeave.FirstApprover = email;
                            paidLeave.SecondApprover = email;
                            _context.Add(paidLeave);
                            await _context.SaveChangesAsync();
                            //send email
                            if (_hostingEnvironment.IsDevelopment())
                            {

EOS.Web/Views/Permit/AddOrEdit.cshtml
@model EOS.Web.Models.PaidLeave
@{
    Layout = null;
}
<script type="text/javascript">
    $(document).ready(function () {
        $('#txtPeriod').change(function () {
            var p = $('#txtPeriod').val();
            var obj = { period: p };
            if (p != 0) {
                $.ajax({
                    type: 'GET',
                    url: "@Url.Action("GetRemainingLeaves","PaidLeaves")",
                    data: obj,
                    success: function (res) {
                        if (res[0].leaveAllowance) {
                            $('#txtTotalLeave').text('Total Cuti :' + res[0].leaveAllowance + ' Hari');
                            $('#txtRemainingLeave').text('Sisa Cuti :' + res[0].remainingLeave + ' Hari');
                        }
                        else {
                            $('#txtTotalLeave').text('Total Cuti :' + res[0].value + ' Hari');
                            $('#txtRemainingLeave').text('Sisa Cuti :' + res[0].value + ' Hari');
                        }
                    }
                });
            }
            else {
                $('#txtTotalLeave').text('Total Cuti : - Hari');
                $('#txtRemainingLeave').text('Sisa Cuti : - Hari');
            }
        });
        $("#txtStartDate, #txtStartFrom, #txtEndTo").change(function () {
            var start = $('#txtStartFrom').val();
            var end = $('#txtEndTo').val();
            if ((end - start) <= 4) {
                $('#txtValue').val(0.5);
                $('#txtCurrentValue').text('Pengajuan Izin :' + 0.5 + ' Hari');
            }
            else {
                $('#txtValue').val(1);
                $('#txtCurrentValue').text('Pengajuan Izin :' + 1 + ' Hari');
            }
        });
    });
</script>
<div class="row">
    <div class="col-md-12">
        <form asp-action="AddOrEdit" asp-route-id="@Model.PaidLeaveId" onsubmit="return jQueryAjaxPost(this);" autocomplete="off">
            <div asp-validation-summary="All" class="text-danger"></div>
            <input type="hidden" asp-for="PaidLeaveId" />
            <input type="hidden" asp-for="Value" id="txtValue" />
            <div class="form-row">
                <div class="form-group col-md-4">
                    <label id="txtTotalLeave" class="control-label font-weight-bold">Total Cuti :<br />- Hari</label>
                </div>
                <div class="form-group col-md-4">
                    <label id="txtRemainingLeave" class="control-label font-weight-bold">Sisa Cuti :<br />- Hari</label>
                </div>
                <div class="form-group col-md-4">
                    <label id="txtCurrentValue" class="control-label font-weight-bold">Pengajuan Cuti :<br />- Hari</label>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label asp-for="@Model.StartDate" class="control-label"></label><span class="required"> *</span>
                    <input asp-for="@Model.StartDate" id="txtStartDate" type="date" asp-format="{0:dd/MM/yyyy}" class="datepicker form-control" value="@Model.StartDate.ToString("dd/MM/yyyy")" min="2021-01-01" />
                    <span asp-validation-for="@Model.StartDate" class="text-danger"></span>
                </div>
                <div class="form-group col-md-3">
                    <label class="control-label">Mulai Jam</label><span class="required"></span>
                    <select name="From" id="txtStartFrom" class="form-control">
                        <option value="0">0</option>
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                        <option value="6">6</option>
                        <option value="7">7</option>
                        <option value="8">8</option>
                        <option value="9">9</option>
                        <option value="10">10</option>
                        <option value="11">11</option>
                        <option value="12">12</option>
                        <option value="13">13</option>
                        <option value="14">14</option>
                        <option value="15">15</option>
                        <option value="16">16</option>
                        <option value="17">17</option>
                        <option value="18">18</option>
                        <option value="19">19</option>
                        <option value="20">20</option>
                        <option value="21">21</option>
                        <option value="22">22</option>
                        <option value="23">23</option>
                    </select>
                </div>
                <div class="form-group col-md-3">
                    <label class="control-label">Sampai Jam</label><span class="required"></span>
                    <select name="To" id="txtEndTo" class="form-control">
                        <option value="0">0</option>
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                        <option value="6">6</option>
                        <option value="7">7</option>
                        <option value="8">8</option>
                        <option value="9">9</option>
                        <option value="10">10</option>
                        <option value="11">11</option>
                        <option value="12">12</option>
                        <option value="13">13</option>
                        <option value="14">14</option>
                        <option value="15">15</option>
                        <option value="16">16</option>
                        <option value="17">17</option>
                        <option value="18">18</option>
                        <option value="19">19</option>
                        <option value="20">20</option>
                        <option value="21">21</option>
                        <option value="22">22</option>
                        <option value="23">23</option>
                    </select>
                </div>
                @*<div class="form-group col-md-6">
            <label asp-for="@Model.EndDate" class="control-label"></label><span class="required"> *</span>
            <input asp-for="@Model.EndDate" id="txtEndDate" type="date" placeholder="dd-mm-yyyy" asp-format="{0:dd/MM/yyyy}" class="datepicker form-control" value="@Model.EndDate.ToString("dd/MM/yyyy")" min="2021-01-01" />
            <span asp-validation-for="@Model.EndDate" class="text-danger"></span>
        </div>*@
            </div>
            <div class="form-group">
                <label asp-for="@Model.PeriodId" class="control-label">Periode</label><span class="required"> *</span>
                <select asp-for="@Model.PeriodId" asp-items="(IEnumerable<SelectListItem>)ViewBag.Period" id="txtPeriod" class="form-control">
                    <option value="0">- Pilih Period Cuti -</option>
                </select>
                <span asp-validation-for="@Model.PeriodId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Remarks" title="Keterangan" class="control-label"></label><span class="required"> *</span>
                <textarea asp-for="Remarks" type="text" rows="3" class="form-control"></textarea>
                <span asp-validation-for="Remarks" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Ajukan Izin" class="btn btn-primary btn-block" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EOS.Web/Views/Permit/Delete.cshtml
@model EOS.Web.Models.PaidLeave

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PaidLeave</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Remarks)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Remarks)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RequestDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RequestDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="PaidLeaveId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

EOS.Web/Views/Permit/Details.cshtml
@model IEnumerable<EOS.Web.Models.ViewPaidLeave>
<div class="row">
    <div class="col-md-12">
        @foreach (var item in Model)
        {
            <div class="form-group row">
                <label class="control-label font-weight-bold col-md-5 col-form-label">Requestor</label>
                <div class="col-md-7">
                    @Html.TextBox("Fullname", item.Fullname, new { id = "txtFullname", @class = "form-control-plaintext", @readonly = "readonly" })
                </div>
            </div>
            <div class="form-group row">
                <label class="control-label font-weight-bold col-md-5 col-form-label">Tanggal Mulai</label>
                <div class="col-md-7">
                    @Html.TextBox("StartDate", item.StartDate.ToString("dd MMM yyyy HH:mm:ss"), new { id = "txtStartDate", @class = "form-control-plaintext", @readonly = "readonly" })
                </div>
            </div>
            <div class="form-group row">
                <label class="control-label font-weight-bold col-md-5 col-form-label">Tanggal Selesai</label>
                <div class="col-md-7">
                    @Html.TextBox("EndDate", item.EndDate.ToString("dd MMM yyyy HH:mm:ss"), new { id = "txtEndDate", @class = "form-control-plaintext", @readonly = "readonly" })
                </div>
            </div>
            <div class="form-group row">
                <label class="control-label font-weight-bold col-md-5 col-form-label">Jumlah Cuti Terpakai</label>
                <div class="col-md-7">
                    @Html.TextBox("Value", item.Value, new { id = "txtValue", @class = "form-control-plaintext", @readonly = "readonly" })
                </div>
            </div>
            <div class="form-group row">
                <label class="control-label font-weight-bold col-md-5 col-form-label">Jenis Cuti</label>
                <div class="col-md-7">
                    @Html.TextBox("PaidLeaveName", item.PaidLeaveName, new { id = "txtPaidLeaveName", @class = "form-control-plaintext", @readonly = "readonly" })
                </div>
            </div>
            <div class="form-group row">
                <label class="control-label font-weight-bold col-md-5 col-form-label">Keperluan Cuti</label>
                <div class="col-md-7">
                    @Html.TextBox("Remarks", item.Remarks, new { id = "txtRemarks", @class = "form-control-plaintext", @readonly = "readonly" })
                </div>
            </div>
            <hr class="red" />
            <h5>Persetujuan</h5>
            <hr class="red" />
            <div class="form-group row">
                <label class="control-label font-weight-bold col-md-5 col-form-label">Approval 1</label>
                <div class="col-md-7">
                    @Html.TextBox("FirstApprover", item.FirstApprover, new { id = "txtFirstApprover", @class = "form-control-plaintext", @readonly = "readonly" })
                </div>
            </div>
            <div class="form-group row">
                <label class="control-label font-weight-bold col-md-5 col-form-label">Waktu Respon</label>
                <div class="col-md-7">
                    @if (item.FirstApproverTimestamp != DateTime.MinValue)
                    {
                        @Html.TextBox("FirstApproverTimestamp", item.FirstApproverTimestamp.ToString("dd MMM yyyy HH:mm:ss"), new { id = "txtFirstApproverTimestamp", @class = "form-control-plaintext", @readonly = "readonly" })
                    }
                </div>
            </div>
            <div class="form-group row">
                <label class="control-label font-weight-bold col-md-5 col-form-label">Respon</label>
                <div class="col-md-7">
                    @Html.TextBox("FirstApproverResponse", item.FirstApproverResponse, new { id = "txtFirstApproverResponse", @class = "form-control-plaintext", @readonly = "readonly" })
                </div>
            </div>
            <div class="form-group row">
                <label class="control-label font-weight-bold col-md-5 col-form-label">Approval 2</label>
                <div class="col-md-7">
                    @Html.TextBox("SecondApprover", item.SecondApprover, new { id = "txtSecondApprover", @class = "form-control-plaintext", @readonly = "readonly" })
                </div>
            </div>
            <div class="form-group row">
                <label class="control-label font-weight-bold col-sm-5 col-form-label">Waktu Respon</label>
                <div class="col-md-7">
                    @if (item.SecondApproverTimestamp != DateTime.MinValue)
                    {
                        @Html.TextBox("SecondApproverTimestamp", item.SecondApproverTimestamp.ToString("dd MMM yyyy HH:mm:ss"), new { id = "txtSecondApproverTimestamp", @class = "form-control-plaintext", @readonly = "readonly" })
                    }
                </div>
            </div>
            <div class="form-group row">
                <label class="control-label font-weight-bold col-md-5 col-form-label">Respon</label>
                <div class="col-md-7">
                    @Html.TextBox("SecondApproverResponse", item.SecondApproverResponse, new { id = "txtSecondApproverResponse", @class = "form-control-plaintext", @readonly = "readonly" })
                </div>
            </div>
        }
    </div>
</div>

EOS.Web/Views/Permit/Index.cshtml
@model EOS.Web.Models.PaidLeave
@{
    ViewData["Title"] = "Pengajuan Izin";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<head>
    @section AddToHead{
        <link rel="stylesheet" href="~/datatables/DataTables-1.10.23/css/dataTables.bootstrap4.min.css" />
        <script src="~/datatables/datatables.min.js"></script>
        <script src="~/moment.js/moment.min.js"></script>
        <script type="text/javascript">
            $(document).ready(function () {
                $("#tbl-grid").DataTable({
                    "processing": false, // for show progress bar
                    "serverSide": true, // for process server side
                    "filter": true, // this is for disable filter (search box)
                    "orderMulti": false, // for disable multiple column at once
                    "language": {
                        "lengthMenu": "Menampilkan _MENU_ baris per halaman",
                        "zeroRecords": "Data tidak ditemukan.",
                        "info": "Menampilkan halaman _PAGE_ dari _PAGES_",
                        "infoEmpty": "Data tidak ditemukan.",
                        "infoFiltered": "(Disaring dari _MAX_ baris)",
                        "search": "Pencarian :",
                        "paginate": {
                            "previous": "Sebelumnya",
                            "next": "Selanjutnya"
                        }
                    },
                    "ajax": {
                        "url": "/Permit/LoadData",
                        "type": "POST",
                        "datatype": "json"
                    },

                    "columnDefs": [{
                        "targets": [0], //hide id
                        "visible": false,
                        "searchable": false
                    },
                    {
                        "targets": [1],
                        "orderable": false
                    }],
                    "columns": [
                        { "data": "paidLeaveId", "name": "PaidLeaveId", "autoWidth": true },
                        {
                            data: null,
                            render: function (data, type, full, meta) {
                                return "<a href='#' class='btn btn-info' onclick=ShowDetail('" + full.paidLeaveId + "');><i class='fas fa-search'></i></a>";
                            }
                        },
                        {
                            data: "startDate", name: "StartDate",
                            render: function (data, type, row) {
                                return moment(row.startDate).format('DD MMM YYYY');
                            }
                        },
                        {
                            data: "endDate", name: "EndDate",
                            render: function (data, type, row) {
                                return moment(row.endDate).format('DD MMM YYYY');
                            }
                        },
                        { "data": "fullName", "name": "Full Name", "autoWidth": true },
                        { "data": "remarks", "name": "Remarks", "autoWidth": true },
                        { "data": "status", "name": "Status", "autoWidth": true },
                        //{
                        //    data: null,
                        //    render: function (data, type, full, meta) {
                        //        return "<a href='#' class='btn btn-info' onclick=UpdateData('" + full.paidLeaveId + "');>Update</a> <a href='#' class='btn btn-danger' onclick=DeleteData('" + full.paidLeaveId + "');>Hapus</a> ";
                        //    }
                        //},
                    ],
                });

            }); //end document ready
            function UpdateData(paidLeaveId) {
                var toSend =
                {
                    id: paidLeaveId
                };
                $.ajax({
                    type: "GET",
                    contentType: "application/json; charset=utf-8",
                    url: "/Permit/AddOrEdit",
                    data: toSend,
                    success: function (res) {
                        $("#form-modal .modal-body").html(res);
                        $("#form-modal .modal-title").html("Ubah");
                        $("#form-modal").modal('show');
                    },
                    error: function (res) {
                        console.log(res);
                    }
                })
            };
            function ShowDetail(paidLeaveId) {
                var toSend =
                {
                    id: paidLeaveId
                };
                $.ajax({
                    type: "GET",
                    contentType: "application/json; charset=utf-8",
                    url: "/Permit/Details",
                    data: toSend,
                    success: function (res) {
                        $("#form-modal .modal-body").html(res.html);
                        $("#form-modal .modal-title").html("Detail Pengajuan Cuti");
                        $("#form-modal").modal('show');
                    },
                    error: function (res) {
                        console.log(res);
                    }
                })
            };
            function DeleteData(bankId) {
                if (confirm('Apakah anda yakin akan menghapus data ini ?')) {
                    var toSend =
                    {
                        id: bankId
                    };
                    $.ajax({
                        type: 'POST',
                        url: '/Permit/Delete',
                        data: toSend,
                        success: function (res) {
                            $.notify('Data berhasil dihapus', { globalPosition: 'bottom right', className: 'success' });
                            oTable = $('#tbl-grid').DataTable();
                            oTable.ajax.reload(null, false);
                        },
                        error: function (err) {
                            console.log(err);
                        }
                    })
                }
            }
        </script>
    }
</head>
<div class="row">
    <div class="col-md-7">
        <h1><i class="fas fa-list-alt text-primary"></i> Pengajuan Izin</h1>
    </div>
    <div class="col-md-5 text-right">
        
        <a onclick="showInPopup('@Url.Action("AddOrEdit", "Permit", new { id = 0 }, Context.Request.Scheme)', 'Pengajuan Izin Baru')" class="btn btn-success btn-sm text-white"><i class="fas fa-plus-circle"></i> Pengajuan Izin Baru</a>
    </div>
    <div class="col-md-12">
        <div id="view-all">
            @await Html.PartialAsync("_ViewAll", Model)
        </div>
    </div>
</div>



@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}